import pandas as pd
import faiss
import datetime
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Función para cargar las preguntas y respuestas del archivo CSV
def cargar_preguntas_respuestas(ruta_csv):
    return pd.read_csv(ruta_csv)

# Función para guardar una nueva pregunta en el archivo CSV
def guardar_pregunta(ruta_csv, pregunta, respuesta):
    df = pd.read_csv(ruta_csv)
    nuevo_df = pd.DataFrame({'Pregunta': [pregunta], 'Respuesta': [respuesta]})
    df = pd.concat([df, nuevo_df], ignore_index=True)
    df.to_csv(ruta_csv, index=False)

# Función para generar embeddings utilizando TF-IDF y crear la base vectorial
def crear_base_vectorial(df):
    vectorizer = TfidfVectorizer()
    preguntas_embeddings = vectorizer.fit_transform(df['Pregunta'])
    
    dimension = preguntas_embeddings.shape[1]
    index = faiss.IndexFlatL2(dimension)
    preguntas_embeddings = preguntas_embeddings.toarray().astype('float32')
    index.add(preguntas_embeddings)
    
    faiss.write_index(index, 'faiss_index.index')
    return index, vectorizer

# Función para clasificar preguntas según su complejidad
def clasificar_pregunta(pregunta):
    preguntas_simples = {
        "Que hora es?": f"La hora actual es {datetime.datetime.now().strftime('%H:%M')}.",
        "De que color es el cielo?": "El cielo generalmente es azul durante el día.",
        "De que color es el mar?": "El mar se ve azul debido a la absorción y dispersión de la luz.",
        "Cual es la capital de Francia?": "La capital de Francia es París.",
        "Cual es la capital de España?": "La capital de España es Madrid.",
        "Que dia es hoy?": f"Hoy es {datetime.datetime.now().strftime('%A')}.",
        "Cual es el resultado de 2+2?": "El resultado de 2+2 es 4.",
        "Cuantos dias tiene una semana?": "Una semana tiene 7 días.",
        "Cuantos meses tiene un año?": "Un año tiene 12 meses.",
        "Que es un perro?": "Un perro es un animal doméstico y una subespecie del lobo.",
        "De que color es una manzana?": "Las manzanas pueden ser rojas, verdes o amarillas.",
        "Que es el sol?": "El sol es una estrella en el centro de nuestro sistema solar.",
        "Cual es la moneda de Estados Unidos?": "La moneda de Estados Unidos es el dólar.",
        "Cuantos continentes hay en el mundo?": "Hay siete continentes en el mundo.",
        "Cuantos planetas hay en el sistema solar?": "Hay ocho planetas en el sistema solar.",
        "Que es la luna?": "La luna es el satélite natural de la Tierra.",
        "De que color es el pasto?": "El pasto generalmente es verde.",
        "Cuantos dientes tiene una persona?": "Un adulto tiene 32 dientes.",
        "Cuantas horas tiene un dia?": "Un día tiene 24 horas.",
        "Cuantos minutos tiene una hora?": "Una hora tiene 60 minutos.",
        "Qué carreras ofrece la Universidad de las Fuerzas Armadas ESPE?": "La ESPE ofrece una variedad de carreras en ingeniería, ciencias de la vida, ciencias administrativas, ciencias de la tierra, y más.",
        "Cuál es el proceso de admisión para la ESPE?": "El proceso de admisión incluye la inscripción en el sistema nacional de nivelación y admisión, la rendición del examen de ingreso, y la selección basada en el puntaje obtenido.",
        "La ESPE acepta estudiantes internacionales?": "Sí, la ESPE acepta estudiantes internacionales bajo ciertas condiciones y requisitos específicos.",
        "Qué programas de postgrado ofrece la ESPE?": "La ESPE ofrece maestrías y doctorados en diversas disciplinas como ingeniería, administración, y ciencias.",
        "Cuál es el costo de la matrícula en la ESPE?": "Los costos varían según la carrera y el nivel de estudio, pero generalmente hay tarifas diferenciadas para estudiantes nacionales e internacionales.",
        "Qué modalidades de estudio ofrece la ESPE?": "La ESPE ofrece modalidades de estudio presencial, semipresencial y a distancia.",
        "Cómo es el sistema de calificaciones en la ESPE?": "El sistema de calificaciones se basa en una escala numérica de 0 a 100, siendo 70 la nota mínima aprobatoria.",
        "La ESPE tiene convenios con otras universidades?": "Sí, la ESPE tiene convenios nacionales e internacionales que permiten intercambios académicos y cooperación en investigación.",
        "Se puede cambiar de carrera una vez admitido en la ESPE?": "Sí, pero el cambio de carrera está sujeto a ciertas condiciones y disponibilidad de cupos en la carrera deseada.",
        "Qué recursos bibliográficos y tecnológicos ofrece la ESPE?": "La ESPE cuenta con una biblioteca central con acceso a recursos digitales, laboratorios equipados, y plataformas virtuales para el aprendizaje.",
        "Dónde está ubicada la ESPE?": "La ESPE tiene varias sedes, con el campus principal ubicado en Sangolquí, cerca de Quito, Ecuador.",
        "Cómo se puede contactar con la ESPE para obtener más información?": "Puedes contactar a la ESPE a través de su página web oficial, teléfono, correo electrónico, o visitando el campus.",
        "La ESPE ofrece becas o ayudas económicas?": "Sí, la ESPE ofrece diversas becas y ayudas económicas basadas en mérito académico y necesidad económica.",
        "Qué servicios de apoyo estudiantil ofrece la ESPE?": "La ESPE ofrece servicios de tutorías, consejería psicológica, orientación vocacional, y actividades extracurriculares.",
        "Qué actividades extracurriculares están disponibles en la ESPE?": "Los estudiantes pueden participar en deportes, clubes estudiantiles, grupos culturales, y proyectos de voluntariado.",
        "Hay residencias estudiantiles en la ESPE?": "Sí, la ESPE ofrece opciones de alojamiento dentro y fuera del campus para estudiantes nacionales e internacionales.",
        "Cómo es la vida en el campus de la ESPE?": "La vida en el campus es dinámica, con diversas actividades académicas, culturales, y deportivas disponibles para los estudiantes.",
        "Qué opciones de transporte existen para llegar a la ESPE?": "Hay varias opciones de transporte público y privado disponibles, incluyendo buses y taxis.",
        "Qué servicios médicos están disponibles para los estudiantes?": "La ESPE cuenta con un centro médico que ofrece atención primaria y servicios de emergencia a los estudiantes.",
        "La ESPE ofrece programas de intercambio estudiantil?": "Sí, la ESPE tiene programas de intercambio con varias universidades alrededor del mundo.",
        "Qué oportunidades de investigación ofrece la ESPE?": "La ESPE fomenta la investigación a través de sus laboratorios y centros de investigación, y ofrece apoyo a proyectos innovadores.",
        "Hay programas de pasantías disponibles para los estudiantes?": "Sí, la ESPE tiene convenios con empresas y organizaciones para que los estudiantes realicen pasantías y prácticas profesionales.",
        "La ESPE organiza conferencias y seminarios?": "La ESPE regularmente organiza conferencias, seminarios y talleres en diversas áreas del conocimiento.",
        "Cómo se puede participar en proyectos de investigación en la ESPE?": "Los estudiantes pueden participar en proyectos de investigación presentando propuestas a los centros de investigación de la universidad.",
        "Qué tipo de apoyo reciben los estudiantes para desarrollar sus investigaciones?": "Los estudiantes reciben apoyo técnico, asesoría académica, y acceso a recursos tecnológicos y bibliográficos.",
        "Cuál es la misión de la Universidad de las Fuerzas Armadas ESPE?": "La misión de la ESPE es formar profesionales de excelencia con valores éticos, liderazgo y compromiso social, contribuyendo al desarrollo científico y tecnológico del país.",
        "Qué tipo de actividades de extensión realiza la ESPE?": "La ESPE realiza actividades de extensión como cursos, talleres, conferencias, y programas comunitarios para promover el conocimiento y el desarrollo social.",
        "Qué idiomas se enseñan en la ESPE?": "Además del español, la ESPE ofrece cursos de inglés y otros idiomas extranjeros como parte de su formación integral.",
        "Cómo se puede acceder a los servicios virtuales de la ESPE?": "Los servicios virtuales están disponibles a través de la plataforma en línea de la ESPE, accesible mediante credenciales proporcionadas a los estudiantes y personal.",
        "Qué apoyo se ofrece a los estudiantes con discapacidad en la ESPE?": "La ESPE cuenta con programas y servicios de apoyo para estudiantes con discapacidad, asegurando accesibilidad y equidad en la educación.",
        "Qué criterios se utilizan para la selección de docentes en la ESPE?": "La selección de docentes se basa en su formación académica, experiencia profesional, y capacidad para la investigación y la enseñanza.",
        "Existen programas de educación continua en la ESPE?": "Sí, la ESPE ofrece programas de educación continua y capacitación para profesionales en diversas áreas.",
        "Cómo se evalúan los cursos en la ESPE?": "Los cursos se evalúan mediante exámenes, trabajos prácticos, proyectos y participación en clase.",
        "Qué opciones de especialización existen en la ESPE?": "La ESPE ofrece especializaciones en áreas como ingeniería, administración, ciencias de la vida, entre otras.",
        "Cuál es la duración de las carreras de pregrado en la ESPE?": "La duración de las carreras de pregrado varía, pero generalmente oscilan entre 4 y 5 años.",
        "Cómo se realiza el pago de la matrícula en la ESPE?": "El pago de la matrícula se puede realizar a través de transferencias bancarias, pagos en línea, o directamente en las oficinas de la universidad.",
        "Cuáles son los requisitos para la graduación en la ESPE?": "Los requisitos incluyen la aprobación de todos los cursos del plan de estudios, la realización de prácticas preprofesionales, y la presentación y defensa de un trabajo de titulación.",
        "Qué documentos se necesitan para la inscripción en la ESPE?": "Se necesitan documentos como el título de bachiller, cédula de identidad, certificado de calificaciones, entre otros.",
        "Cómo se puede obtener una copia del historial académico en la ESPE?": "Las copias del historial académico se pueden solicitar en la Secretaría Académica de la universidad.",
        "La ESPE ofrece servicios de alimentación en el campus?": "Sí, la ESPE cuenta con cafeterías y comedores que ofrecen servicios de alimentación a los estudiantes y personal.",
        "Cómo se puede participar en actividades deportivas en la ESPE?": "Los estudiantes pueden inscribirse en los equipos deportivos o participar en las actividades organizadas por el departamento de deportes de la universidad.",
        "Qué opciones de entretenimiento hay cerca del campus de la ESPE?": "Cerca del campus hay opciones de entretenimiento como cines, centros comerciales, parques y restaurantes.",
        "Cómo se gestionan las actividades culturales en la ESPE?": "Las actividades culturales son gestionadas por el departamento de cultura, que organiza eventos, talleres y presentaciones artísticas.",
        "La ESPE tiene algún código de vestimenta para los estudiantes?": "No hay un código de vestimenta estricto, pero se espera que los estudiantes vistan de manera apropiada y respetuosa.",
        "Qué facilidades deportivas ofrece la ESPE?": "La ESPE cuenta con canchas de fútbol, baloncesto, voleibol, gimnasio y otras instalaciones deportivas.",
        "Qué áreas de investigación son prioritarias en la ESPE?": "Las áreas prioritarias incluyen ingeniería, tecnología, ciencias de la vida, ciencias administrativas, y ciencias de la tierra.",
        "Qué apoyo financiero está disponible para proyectos de investigación en la ESPE?": "La ESPE ofrece financiamiento a través de fondos internos, así como la posibilidad de aplicar a fondos externos y becas.",
        "Cómo se puede publicar un trabajo de investigación realizado en la ESPE?": "Los trabajos de investigación se pueden publicar en revistas académicas, conferencias, y otros medios aprobados por la universidad.",
        "Qué programas de innovación y emprendimiento ofrece la ESPE?": "La ESPE cuenta con programas de incubación de empresas, asesoramiento en emprendimiento, y apoyo a la innovación tecnológica.",
        "Cómo se fomenta la colaboración internacional en investigación en la ESPE?": "La ESPE fomenta la colaboración internacional a través de convenios con universidades extranjeras, participación en proyectos conjuntos y movilidad académica.",
        "Qué valores promueve la Universidad de las Fuerzas Armadas ESPE?": "La ESPE promueve valores como la disciplina, el respeto, la responsabilidad, la integridad, y el compromiso social.",
        "Qué reconocimiento tiene la ESPE a nivel nacional e internacional?": "La ESPE es reconocida por su calidad académica y sus contribuciones en investigación e innovación, tanto a nivel nacional como internacional.",
        "Cuál es el impacto de los egresados de la ESPE en la sociedad?": "Los egresados de la ESPE tienen un impacto significativo en la sociedad al contribuir con sus conocimientos y habilidades en diversos campos profesionales.",
        "La ESPE tiene programas de formación continua para sus egresados?": "Sí, la ESPE ofrece programas de formación continua para que los egresados actualicen sus conocimientos y habilidades.",
        "Qué es el sistema de autoevaluación institucional de la ESPE?":"Es un proceso continuo de evaluación interna que busca mejorar la calidad educativa y administrativa de la universidad.",
        "Qué programas de formación continua existen en la ESPE?":"La ESPE ofrece cursos, diplomados, talleres y seminarios para la actualización y capacitación profesional continua.",
        "Qué tipo de acreditaciones académicas tiene la ESPE?":"La ESPE está acreditada por el Consejo de Aseguramiento de la Calidad de la Educación Superior (CACES) y otros organismos nacionales e internacionales.",
        "Cómo se realizan las prácticas de laboratorio en la ESPE?":"Las prácticas de laboratorio se realizan en instalaciones especializadas y son guiadas por profesores y técnicos especializados.",
        "Qué convenios de doble titulación tiene la ESPE?":"La ESPE tiene convenios de doble titulación con universidades en Europa, Asia y América del Norte.",
        "Cómo es el proceso de titulación en la ESPE?":"El proceso de titulación incluye la realización de un proyecto de fin de carrera, defensa de tesis o examen complexivo, dependiendo del programa.",
        "Qué herramientas tecnológicas utilizan los estudiantes en la ESPE?":"Los estudiantes utilizan herramientas como plataformas de elearning, software especializado según sus carreras, y acceso a bibliotecas digitales.",
        "Qué es el programa de mentoría entre pares de la ESPE?":"Es un programa donde estudiantes de niveles avanzados apoyan a sus compañeros de niveles inferiores en aspectos académicos y de adaptación universitaria.",
        "Qué programas de intercambio académico nacional tiene la ESPE?":"La ESPE tiene programas de intercambio con universidades dentro de Ecuador que permiten a los estudiantes cursar semestres en otras instituciones del país.",
        "Qué es el Consejo Académico de la ESPE?":"Es el organismo encargado de tomar decisiones sobre políticas académicas, planes de estudio y asuntos relacionados con la educación en la universidad.",
        "Qué métodos de evaluación continua se aplican en la ESPE?":"Se aplican métodos como exámenes periódicos, trabajos prácticos, proyectos, presentaciones y participación en clase.",
        "Cómo se gestionan las inscripciones en la ESPE?":"Las inscripciones se gestionan a través de un sistema en línea donde los estudiantes pueden registrar sus materias y horarios.",
        "Qué es el registro académico en la ESPE?":"El registro académico es el proceso de inscripción y seguimiento de los cursos y calificaciones de los estudiantes durante su trayectoria universitaria.",
        "Qué tipo de atención a estudiantes ofrece la ESPE?":"La ESPE ofrece atención personalizada a través de sus oficinas de bienestar estudiantil, orientación académica y tutorías.",
        "Cómo se puede solicitar una revisión de calificaciones en la ESPE?":"Los estudiantes pueden solicitar una revisión de calificaciones presentando una solicitud formal a la Secretaría Académica dentro del plazo establecido.",
        "Qué es el sistema de tutorías académicas en la ESPE?":"Es un sistema donde profesores asignados brindan apoyo y seguimiento personalizado a los estudiantes para mejorar su rendimiento académico.",
        "Qué procedimientos existen para cambiar de carrera en la ESPE?":"Los estudiantes pueden solicitar un cambio de carrera mediante una solicitud formal, evaluación de sus calificaciones y disponibilidad de cupos en la nueva carrera.",
        "Cómo se gestionan las actividades extracurriculares en la ESPE?":"Las actividades extracurriculares son coordinadas por el departamento de bienestar estudiantil y abarcan áreas deportivas, culturales y sociales.",
        "Qué servicios ofrece la Secretaría General de la ESPE?":"La Secretaría General gestiona los procesos administrativos, certificaciones, registros académicos y atención al estudiante.",
        "Qué es el sistema de bienestar universitario en la ESPE?":"Es un conjunto de servicios y programas destinados a promover el bienestar físico, emocional y social de los estudiantes.",
        "Qué programas de apoyo a la empleabilidad ofrece la ESPE?":"La ESPE ofrece talleres de empleabilidad, ferias de empleo, orientación profesional y convenios con empresas para prácticas y empleo.",
        "Qué programas de liderazgo estudiantil existen en la ESPE?":"La ESPE promueve programas de liderazgo a través de actividades, talleres y grupos estudiantiles enfocados en el desarrollo de habilidades de liderazgo.",
        "Cómo se celebran las fiestas universitarias en la ESPE?":"La ESPE organiza eventos y celebraciones que incluyen festivales culturales, deportivos y académicos en los que participan toda la comunidad universitaria.",
        "Qué medidas de sostenibilidad ambiental promueve la ESPE?":"La ESPE implementa prácticas de reciclaje, ahorro de energía, uso eficiente del agua y programas de educación ambiental.",
        "Qué servicios de orientación vocacional están disponibles en la ESPE?":"Los servicios incluyen asesoramiento personalizado, talleres de orientación, y pruebas de aptitudes y habilidades para ayudar a los estudiantes en su elección de carrera.",
        "Qué tipo de programas de voluntariado se ofrecen en la ESPE?":"Los programas de voluntariado abarcan áreas como educación, salud, medio ambiente y desarrollo comunitario, permitiendo a los estudiantes contribuir a la sociedad.",
        "Qué eventos deportivos se organizan en la ESPE?":"La ESPE organiza campeonatos internos, torneos interuniversitarios y participa en competencias nacionales e internacionales.",
        "Cómo se promueve la integración de estudiantes nuevos en la ESPE?":"La ESPE tiene programas de inducción, actividades de bienvenida y mentoría para ayudar a los nuevos estudiantes a adaptarse a la vida universitaria.",
        "Qué actividades culturales se realizan en la ESPE?":"Se realizan actividades como conciertos, obras de teatro, exposiciones de arte y festivales culturales que involucran a la comunidad universitaria.",
        "Qué es la semana de la ciencia y tecnología en la ESPE?":"Es un evento anual donde se presentan proyectos de investigación, innovación tecnológica y se realizan conferencias y talleres relacionados con ciencia y tecnología.",
        "Qué programas de intercambio cultural existen en la ESPE?":"La ESPE tiene programas de intercambio cultural que permiten a los estudiantes conocer y participar en actividades culturales de otros países.",
        "Qué tipo de centros de investigación tiene la ESPE?":"La ESPE cuenta con centros de investigación en áreas como biotecnología, robótica, energías renovables, entre otros.",
        "Qué es el sistema de investigación aplicada en la ESPE?":"Es un sistema que promueve la investigación orientada a resolver problemas prácticos y contribuir al desarrollo tecnológico e industrial.",
        "Qué tipo de seminarios y conferencias organiza la ESPE?":"La ESPE organiza seminarios y conferencias en diversas áreas del conocimiento, invitando a expertos nacionales e internacionales.",
        "Cómo se puede participar en los proyectos de investigación de la ESPE?":"Los estudiantes pueden participar presentando propuestas de investigación, unirse a proyectos existentes o colaborar con profesores investigadores.",
        "Qué publicaciones científicas produce la ESPE?":"La ESPE publica revistas académicas, libros, artículos científicos y actas de conferencias en diversas disciplinas.",
        "Qué es el programa de jóvenes investigadores de la ESPE?":"Es un programa que incentiva a los estudiantes a iniciar su carrera investigativa mediante la participación en proyectos de investigación desde etapas tempranas de su formación.",
        "Qué tipo de convenios de investigación tiene la ESPE?":"La ESPE tiene convenios con instituciones académicas, centros de investigación y empresas tanto a nivel nacional como internacional.",
        "Qué premios y reconocimientos existen para los investigadores de la ESPE?":"La ESPE otorga premios y reconocimientos a la excelencia investigativa, a la innovación y a la publicación de artículos científicos de alto impacto.",
        "Qué es el fondo de investigación de la ESPE?":"Es un fondo destinado a financiar proyectos de investigación, adquisición de equipos y materiales, y la difusión de resultados.",
        "Qué programas de investigación interdisciplinaria existen en la ESPE?":"La ESPE promueve la investigación interdisciplinaria que involucra a diversas áreas del conocimiento para abordar problemas complejos y desarrollar soluciones innovadoras.",
        "Cómo se celebran los aniversarios de la ESPE?":"Los aniversarios se celebran con eventos académicos, deportivos, culturales y sociales que involucran a toda la comunidad universitaria.",
        "Qué es el sistema de tutorías virtuales en la ESPE?":"Es un sistema que permite a los estudiantes recibir tutorías y asesorías académicas en línea a través de plataformas digitales.",
        "Qué programas de desarrollo personal ofrece la ESPE?":"La ESPE ofrece talleres y cursos de desarrollo personal que abarcan temas como liderazgo, habilidades comunicativas, gestión del tiempo y más.",
        "Cómo se gestionan las prácticas profesionales en la ESPE?":"Las prácticas profesionales se gestionan a través de convenios con empresas e instituciones, permitiendo a los estudiantes adquirir experiencia laboral.",
        "Qué programas de intercambio científico tiene la ESPE?":"La ESPE promueve el intercambio científico mediante la participación en proyectos internacionales, conferencias y publicaciones conjuntas.",
        "Qué recursos bibliográficos ofrece la biblioteca de la ESPE?":"La biblioteca ofrece libros, revistas, bases de datos, recursos digitales y servicios de préstamo interbibliotecario.",
        "Cómo se promueve la cultura emprendedora en la ESPE?":"La ESPE fomenta la cultura emprendedora a través de programas de formación, incubadoras de empresas y asesoramiento para el desarrollo de proyectos emprendedores.",
        "Qué programas de actualización docente existen en la ESPE?":"La ESPE ofrece programas de actualización y formación continua para sus docentes, incluyendo cursos, talleres y seminarios.",
        "Qué es el programa de movilidad académica de la ESPE?":"Es un programa que permite a los estudiantes realizar parte de sus estudios en universidades extranjeras con las que la ESPE tiene convenios.",
        "Qué tipo de residencias estudiantiles ofrece la ESPE?":"La ESPE cuenta con residencias estudiantiles que ofrecen alojamiento a estudiantes de otras ciudades y países, con servicios básicos y áreas comunes.",
        "Qué programas de doble modalidad ofrece la ESPE?":"La ESPE ofrece programas de doble modalidad que combinan estudios presenciales y a distancia, facilitando la flexibilidad académica.",
        "Cómo se gestionan las clases virtuales en la ESPE?":"Las clases virtuales se gestionan a través de plataformas de elearning que permiten el acceso a contenidos, interacción con profesores y compañeros, y evaluación en línea.",
        "Qué es el sistema de créditos transferibles de la ESPE?":"Es un sistema que permite a los estudiantes transferir créditos académicos obtenidos en otras instituciones nacionales e internacionales.",
        "Qué programas de formación técnica ofrece la ESPE?":"La ESPE ofrece programas de formación técnica en áreas como mecánica, electrónica, informática y más, con un enfoque en la práctica y la aplicación.",
        "Qué tipos de programas de maestría ofrece la ESPE?":"La ESPE ofrece maestrías en áreas como ingeniería, administración, ciencias de la salud, educación, entre otras.",
        "Cómo se puede acceder a los cursos de idiomas de la ESPE?":"Los cursos de idiomas se pueden acceder a través del departamento de lenguas extranjeras, que ofrece programas en inglés, francés, alemán, chino, y otros.",
        "Qué es el sistema de evaluación por competencias en la ESPE?":"Es un sistema que evalúa a los estudiantes en base a las competencias adquiridas y su aplicación práctica en situaciones reales.",
        "Qué programas de doctorado ofrece la ESPE?":"La ESPE ofrece programas de doctorado en diversas áreas del conocimiento, enfocados en la investigación avanzada y la innovación.",
        "Cómo se gestionan los programas de pasantías internacionales en la ESPE?":"Los programas de pasantías internacionales se gestionan a través de convenios con empresas y organizaciones en el extranjero, ofreciendo a los estudiantes la oportunidad de adquirir experiencia global.",
        "Qué es el sistema de calificaciones en la ESPE?":"El sistema de calificaciones se basa en una escala numérica y cualitativa, evaluando el rendimiento académico a través de exámenes, proyectos y participación en clase.",
        "Qué es el departamento de bienestar estudiantil de la ESPE?":"Es una unidad encargada de ofrecer servicios y programas que promuevan el bienestar físico, emocional y social de los estudiantes.",
        "Qué procedimientos se siguen para la revalidación de estudios en la ESPE?":"La revalidación de estudios se realiza a través de un proceso de evaluación de los programas cursados en otras instituciones y la equivalencia con los de la ESPE.",
        "Cómo se puede acceder a los servicios de asesoría legal en la ESPE?":"Los servicios de asesoría legal están disponibles para los estudiantes a través de la oficina de bienestar universitario, ofreciendo orientación en temas legales y académicos.",
        "Qué programas de apoyo a la maternidad y paternidad existen en la ESPE?":"La ESPE ofrece programas de apoyo para estudiantes que son padres o madres, incluyendo facilidades académicas y acceso a servicios de cuidado infantil.",
        "Cómo se puede solicitar una baja temporal en la ESPE?":"Los estudiantes pueden solicitar una baja temporal presentando una solicitud formal a la Secretaría Académica y justificando su motivo.",
        "Qué es el sistema de evaluación docente en la ESPE?":"Es un sistema que permite evaluar el desempeño de los docentes a través de encuestas a estudiantes, autoevaluaciones y observaciones.",
        "Cómo se gestionan las actividades de extensión universitaria en la ESPE?":"Las actividades de extensión universitaria son coordinadas por el departamento de extensión, involucrando a estudiantes y docentes en proyectos comunitarios y culturales.",
        "Qué servicios de orientación académica ofrece la ESPE?":"La ESPE ofrece servicios de orientación académica para ayudar a los estudiantes en la planificación de su carrera y en la toma de decisiones académicas.",
        "Cómo se puede acceder a los servicios de bibliotecas en la ESPE?":"Los estudiantes pueden acceder a los servicios de bibliotecas presentando su carnet estudiantil y utilizando los recursos disponibles en línea y presencialmente.",
        "Qué programas de formación en competencias digitales existen en la ESPE?":"La ESPE ofrece programas de formación en competencias digitales que incluyen cursos de informática, programación, diseño web y manejo de herramientas digitales.",
        "Qué servicios de cafetería están disponibles en la ESPE?":"La ESPE cuenta con varias cafeterías y comedores que ofrecen una variedad de alimentos y bebidas a precios accesibles para los estudiantes.",
        "Qué actividades de integración para estudiantes internacionales existen en la ESPE?":"La ESPE organiza actividades de integración, como orientaciones, excursiones y eventos culturales para estudiantes internacionales.",
        "Qué es el programa de embajadores estudiantiles de la ESPE?":"Es un programa donde estudiantes destacados representan a la universidad en eventos, ferias y actividades promocionales.",
        "Cómo se promueve la participación estudiantil en la ESPE?":"La participación estudiantil se promueve a través de organizaciones estudiantiles, consejos, clubes y actividades extracurriculares.",
        "Qué programas de apoyo a la salud mental ofrece la ESPE?":"La ESPE ofrece programas de apoyo a la salud mental que incluyen consejería, talleres de manejo del estrés y grupos de apoyo.",
        "Qué tipo de actividades artísticas se fomentan en la ESPE?":"Se fomentan actividades como música, danza, teatro, pintura y fotografía, con grupos y talleres disponibles para los estudiantes.",
        "Cómo se organizan las ferias estudiantiles en la ESPE?":"Las ferias estudiantiles son organizadas por el consejo estudiantil y otras organizaciones, presentando proyectos, productos y servicios de los estudiantes.",
        "Qué programas de intercambio deportivo tiene la ESPE?":"La ESPE tiene programas de intercambio deportivo que permiten a los estudiantes participar en competencias y entrenamientos en otras universidades y países.",
        "Qué es el programa de desarrollo de habilidades blandas en la ESPE?":"Es un programa que ofrece talleres y cursos para desarrollar habilidades blandas como comunicación, trabajo en equipo, liderazgo y resolución de problemas.",
        "Qué medidas de seguridad existen en el campus de la ESPE?":"La ESPE cuenta con sistemas de vigilancia, control de acceso, y personal de seguridad para garantizar la seguridad de toda la comunidad universitaria.",
        "Qué es el fondo de innovación de la ESPE?":"Es un fondo destinado a financiar proyectos innovadores y de emprendimiento desarrollados por estudiantes y profesores.",
        "Cómo se promueve la transferencia tecnológica en la ESPE?":"La ESPE promueve la transferencia tecnológica a través de la colaboración con la industria, la protección de propiedad intelectual y la comercialización de tecnologías.",
        "Qué es el programa de cátedras de investigación en la ESPE?":"Es un programa que promueve la creación de cátedras en áreas específicas de investigación, lideradas por expertos y financiadas por la universidad y entidades externas.",
        "Qué proyectos de desarrollo sostenible se realizan en la ESPE?":"La ESPE realiza proyectos de desarrollo sostenible en áreas como energías renovables, gestión de residuos, y conservación ambiental.",
        "Cómo se gestionan los laboratorios de investigación en la ESPE?":"Los laboratorios de investigación son gestionados por departamentos especializados, que coordinan el uso de equipos, recursos y la realización de experimentos.",
        "Qué es el programa de incubadoras de empresas de la ESPE?":"Es un programa que apoya a estudiantes y emprendedores en el desarrollo de sus proyectos empresariales, ofreciendo asesoramiento, recursos y espacio físico.",
        "Qué tipo de investigaciones se realizan en el área de ciencias de la salud en la ESPE?":"Se realizan investigaciones en áreas como medicina, biotecnología, salud pública y nutrición, enfocadas en mejorar la salud y el bienestar de la población.",
        "Cómo se fomenta la investigación en humanidades y ciencias sociales en la ESPE?":"Se fomenta a través de proyectos de investigación, publicaciones, y la participación en congresos y seminarios.",
        "Qué programas de apoyo a la investigación estudiantil existen en la ESPE?":"Existen programas que ofrecen financiamiento, asesoría y recursos para que los estudiantes desarrollen sus propios proyectos de investigación.",
        "Qué es el sistema de patentes y propiedad intelectual en la ESPE?":"Es un sistema que protege las invenciones y desarrollos tecnológicos de la universidad, promoviendo la innovación y la transferencia de tecnología.",
        "Qué es el programa de becas de excelencia académica en la ESPE?":"Es un programa que otorga becas a estudiantes con alto rendimiento académico para apoyar sus estudios.",
        "Cómo se puede participar en los programas de voluntariado en la ESPE?":"Los estudiantes pueden participar inscribiéndose en los programas disponibles a través del departamento de bienestar estudiantil.",
        "Qué servicios de apoyo a la discapacidad ofrece la ESPE?":"La ESPE ofrece servicios de apoyo como accesibilidad en instalaciones, asesoramiento y recursos educativos adaptados.",
        "Cómo se gestionan las residencias estudiantiles en la ESPE?":"Las residencias son gestionadas por la administración de la universidad, ofreciendo alojamiento y servicios básicos a los estudiantes.",
        "Qué es el programa de mentores académicos en la ESPE?":"Es un programa donde profesores y profesionales guían y apoyan a los estudiantes en su desarrollo académico y profesional.",
        "Qué medidas de inclusión social promueve la ESPE?":"La ESPE promueve la inclusión social a través de programas de becas, apoyo a estudiantes de comunidades marginadas y políticas de equidad.",
        "Qué es el sistema de evaluación continua en la ESPE?":"Es un sistema que evalúa el rendimiento de los estudiantes a lo largo del semestre mediante exámenes, proyectos, y participación en clase.",
        "Cómo se puede acceder a los servicios de salud en la ESPE?":"Los estudiantes pueden acceder a los servicios de salud presentando su carnet estudiantil en el centro médico de la universidad.",
        "Qué programas de actualización profesional ofrece la ESPE?":"La ESPE ofrece programas de actualización profesional en diversas áreas, incluyendo cursos, diplomados y certificaciones.",
        "Qué es el programa de tutorías entre pares en la ESPE?":"Es un programa donde estudiantes avanzados apoyan a sus compañeros en temas académicos y de adaptación universitaria.",
        "Qué programas de formación en línea ofrece la ESPE?":"La ESPE ofrece programas de formación en línea que incluyen cursos, diplomados y maestrías en diversas áreas del conocimiento.",
        "Cómo se puede acceder a los cursos de educación continua en la ESPE?":"Los interesados pueden inscribirse a través del departamento de educación continua, que ofrece una variedad de cursos y talleres.",
        "Qué tipo de certificaciones profesionales ofrece la ESPE?":"La ESPE ofrece certificaciones profesionales en áreas como tecnología, administración, salud y más, validando competencias específicas.",
        "Qué es el sistema de evaluación por proyectos en la ESPE?":"Es un sistema que evalúa a los estudiantes mediante la realización de proyectos que integran conocimientos y habilidades adquiridas.",
        "Qué programas de formación en habilidades técnicas ofrece la ESPE?":"La ESPE ofrece programas de formación en habilidades técnicas como programación, diseño gráfico, mecánica y más.",
        "Qué es el sistema de formación dual en la ESPE?":"Es un sistema que combina formación académica con prácticas laborales en empresas, facilitando la inserción laboral de los estudiantes.",
        "Qué tipo de apoyo reciben los estudiantes internacionales en la ESPE?":"Los estudiantes internacionales reciben apoyo en su proceso de adaptación, orientación académica, y acceso a servicios universitarios.",
        "Qué es el programa de aceleración de startups de la ESPE?":"Es un programa que apoya a emprendedores en el desarrollo y crecimiento rápido de sus startups mediante mentoría, recursos y financiamiento.",
        "Qué servicios de asesoría académica están disponibles en la ESPE?":"Los servicios de asesoría académica incluyen orientación en la elección de carrera, planificación de estudios y apoyo en la resolución de problemas académicos.",
        "Qué es el sistema de calificaciones por competencias en la ESPE?":"Es un sistema que evalúa a los estudiantes en base a las competencias desarrolladas y su capacidad para aplicarlas en situaciones prácticas.",
        "Cómo se gestionan las becas en la ESPE?":"Las becas se gestionan a través de un proceso de selección basado en mérito académico, necesidades económicas y otras categorías específicas.",
        "Qué servicios de atención al estudiante ofrece la ESPE?":"La ESPE ofrece servicios de atención al estudiante que incluyen orientación académica, apoyo psicológico, y asesoría legal.",
        "Cómo se puede solicitar una transferencia a la ESPE?":"Los estudiantes pueden solicitar una transferencia presentando su historial académico y cumpliendo con los requisitos establecidos por la universidad.",
        "Qué es el sistema de gestión académica en la ESPE?":"Es un sistema que permite a los estudiantes y docentes gestionar inscripciones, calificaciones, y otros procesos académicos en línea.",
        "Qué servicios de orientación vocacional ofrece la ESPE?":"Los servicios incluyen asesoramiento personalizado, pruebas de aptitudes y talleres para ayudar a los estudiantes en su elección de carrera.",
        "Cómo se puede acceder a los servicios de transporte de la ESPE?":"Los servicios de transporte se pueden acceder mediante inscripción en los puntos de información y están disponibles para facilitar el desplazamiento dentro y fuera del campus.",
        "Qué es el programa de mentoría profesional en la ESPE?":"Es un programa donde profesionales y exalumnos exitosos guían a los estudiantes en su desarrollo profesional y planificación de carrera.",
        "Qué tipo de actividades de integración para nuevos estudiantes existen en la ESPE?":"Existen actividades como programas de inducción, talleres de orientación y eventos de bienvenida para ayudar a los nuevos estudiantes a integrarse.",
        "Qué es el sistema de gestión de prácticas profesionales en la ESPE?":"Es un sistema que coordina las prácticas profesionales de los estudiantes, facilitando la conexión con empresas y seguimiento de su desempeño.",
        "Qué programas de movilidad académica nacional tiene la ESPE?":"La ESPE tiene programas de movilidad académica que permiten a los estudiantes cursar parte de sus estudios en otras universidades del país.",
        "Qué servicios de comedor están disponibles en la ESPE?":"La ESPE cuenta con comedores que ofrecen menús variados y nutritivos a precios accesibles para los estudiantes.",
        "Qué tipo de actividades recreativas se promueven en la ESPE?":"Se promueven actividades recreativas como deportes, clubes, talleres artísticos y eventos sociales.",
        "Cómo se pueden formar clubes estudiantiles en la ESPE?":"Los estudiantes pueden formar clubes presentando una solicitud con los objetivos del club y la lista de miembros interesados.",
        "Qué programas de apoyo a la empleabilidad existen en la ESPE?":"La ESPE ofrece talleres de empleabilidad, ferias de empleo y servicios de orientación profesional para ayudar a los estudiantes en su inserción laboral.",
        "Qué es el programa de tutorías deportivas en la ESPE?":"Es un programa donde deportistas destacados brindan entrenamiento y apoyo a sus compañeros en diferentes disciplinas deportivas.",
        "Cómo se promueve la participación en proyectos comunitarios en la ESPE?":"La participación se promueve a través de programas de voluntariado, prácticas comunitarias y proyectos de extensión universitaria.",
        "Qué es el sistema de becas de alimentación en la ESPE?":"Es un sistema que ofrece becas a estudiantes de bajos recursos para acceder a los servicios de comedor universitario.",
        "Qué servicios de lavandería están disponibles en las residencias estudiantiles de la ESPE?":"Las residencias estudiantiles cuentan con servicios de lavandería disponibles para los residentes.",
        "Cómo se pueden acceder a los servicios de atención psicológica en la ESPE?":"Los servicios de atención psicológica están disponibles a través del departamento de bienestar estudiantil y se accede mediante cita previa.",
        "Qué tipo de actividades de voluntariado internacional promueve la ESPE?":"La ESPE promueve actividades de voluntariado internacional en áreas como educación, salud, desarrollo comunitario y medio ambiente.",
        "Qué es el programa de financiación de proyectos de investigación en la ESPE?":"Es un programa que otorga fondos para el desarrollo de proyectos de investigación presentados por estudiantes y profesores.",
        "Cómo se fomenta la colaboración con la industria en la ESPE?":"Se fomenta a través de convenios, proyectos conjuntos, y programas de transferencia tecnológica y prácticas profesionales.",
        "Qué es el programa de becas de investigación en la ESPE?":"Es un programa que otorga becas a estudiantes y profesores para realizar investigaciones en diversas áreas del conocimiento.",
        "Qué tipo de investigaciones se realizan en el área de ingenierías en la ESPE?":"Se realizan investigaciones en áreas como robótica, energías renovables, telecomunicaciones, materiales y más.",
        "Cómo se promueve la difusión de resultados de investigación en la ESPE?":"Se promueve a través de publicaciones en revistas científicas, congresos, seminarios y plataformas digitales.",
        "Qué es el programa de cátedras internacionales en la ESPE?":"Es un programa que invita a profesores y expertos internacionales a impartir cátedras y colaborar en proyectos de investigación.",
        "Cómo se apoya a los investigadores jóvenes en la ESPE?":"Se apoya a través de programas de mentoría, financiamiento de proyectos y oportunidades de formación y desarrollo profesional.",
        "Qué tipo de laboratorios especializados existen en la ESPE?":"Existen laboratorios especializados en áreas como biotecnología, nanotecnología, energías renovables, simulación y más.",
        "Qué es el programa de pasantías de investigación en la ESPE?":"Es un programa que ofrece a los estudiantes la oportunidad de realizar pasantías en proyectos de investigación, tanto dentro como fuera del país.",
        "Cómo se gestionan las redes de investigación en la ESPE?":"Las redes de investigación se gestionan a través de la colaboración entre diferentes departamentos, instituciones y proyectos conjuntos.",
        "Qué es el programa de becas para investigación aplicada en la ESPE?":"Es un programa que proporciona becas para proyectos de investigación que tengan aplicaciones prácticas y soluciones innovadoras.",
        "Cómo se facilita la internacionalización de la investigación en la ESPE?":"Se facilita mediante convenios internacionales, participación en redes globales y colaboración en proyectos de investigación transnacionales.",
        "Qué tipo de colaboración tiene la ESPE con otras universidades?":"La ESPE colabora con otras universidades en proyectos de investigación, intercambios académicos, programas conjuntos y actividades de desarrollo profesional.",
        "Cómo se fomenta la innovación tecnológica en la ESPE?":"Se fomenta mediante el apoyo a proyectos innovadores, incubadoras de startups, y colaboración con empresas tecnológicas y centros de investigación.",
        "Qué es el programa de becas para proyectos de innovación en la ESPE?":"Es un programa que ofrece becas para apoyar el desarrollo y la implementación de proyectos innovadores en distintas áreas del conocimiento.",
        "Cómo se puede participar en las ferias de ciencia y tecnología de la ESPE?":"Los estudiantes pueden participar inscribiéndose en las convocatorias de las ferias, presentando sus proyectos y trabajos de investigación.",
        "Qué servicios de apoyo para el emprendimiento ofrece la ESPE?":"La ESPE ofrece servicios como asesoría para la creación de empresas, mentoría, recursos para el desarrollo de proyectos y apoyo financiero.",
        "Qué es el programa de incubadoras de empresas en la ESPE?":"Es un programa que apoya a emprendedores en el lanzamiento y crecimiento de sus empresas mediante asesoría, recursos y acceso a redes de contacto.",
        "Cómo se puede acceder a los recursos de las incubadoras de empresas en la ESPE?":"Se puede acceder a través de un proceso de selección y aplicación que evalúa la viabilidad y el potencial del proyecto emprendedor.",
        "Qué es el programa de apoyo a la transferencia de tecnología en la ESPE?":"Es un programa que facilita la transferencia de innovaciones tecnológicas desde el ámbito académico hacia el mercado y la industria.",
        "Cómo se promueve la colaboración entre empresas y la ESPE?":"Se promueve mediante convenios de colaboración, proyectos conjuntos de investigación y desarrollo, y programas de prácticas profesionales.",
        "Qué es el programa de becas para estudiantes emprendedores en la ESPE?":"Es un programa que ofrece becas a estudiantes que están desarrollando sus propias iniciativas empresariales o proyectos innovadores.",
        "Qué tipo de eventos de networking organiza la ESPE?":"La ESPE organiza eventos de networking como ferias de empleo, conferencias, y encuentros con empresarios y profesionales del sector.",
        "Cómo se pueden acceder a las oportunidades de formación continua en la ESPE?":"Se pueden acceder mediante la inscripción en los cursos y programas ofrecidos por el departamento de educación continua de la universidad.",
        "Qué tipo de actividades culturales y artísticas promueve la ESPE?":"Se promueven actividades como exposiciones, conciertos, representaciones teatrales y talleres artísticos.",
        "Cómo se puede participar en los eventos culturales de la ESPE?":"Los estudiantes pueden participar inscribiéndose en las actividades a través del departamento de cultura o asistiendo a los eventos programados.",
        "Qué es el programa de becas de movilidad internacional en la ESPE?":"Es un programa que ofrece becas para que los estudiantes puedan participar en intercambios académicos y programas de estudio en el extranjero.",
        "Cómo se pueden solicitar las becas de movilidad internacional en la ESPE?":"Las solicitudes se realizan a través del departamento de movilidad académica, cumpliendo con los requisitos y plazos establecidos.",
        "Qué tipo de apoyo se ofrece para el desarrollo de proyectos científicos en la ESPE?":"Se ofrece apoyo financiero, acceso a recursos y equipos de laboratorio, y asesoría de expertos para el desarrollo de proyectos científicos.",
        "Qué es el programa de mentoría para investigadores en la ESPE?":"Es un programa que brinda apoyo y orientación a los investigadores jóvenes mediante la mentoría de académicos y profesionales experimentados.",
        "Cómo se puede participar en las actividades de divulgación científica de la ESPE?":"Se puede participar presentando investigaciones y proyectos en eventos organizados por la universidad y colaborando en publicaciones científicas.",
        "Qué tipo de oportunidades de investigación se ofrecen a los estudiantes de la ESPE?":"Se ofrecen oportunidades para participar en proyectos de investigación, pasantías y colaboraciones con grupos de investigación y centros académicos.",
        "Qué es el programa de becas para estudios de posgrado en la ESPE?":"Es un programa que proporciona becas para estudios de maestría y doctorado en áreas específicas de conocimiento.",
        "Cómo se puede acceder a las becas para estudios de posgrado en la ESPE?":"Se puede acceder mediante la presentación de una solicitud, que incluye una propuesta de investigación y cumplimiento de los requisitos académicos.",
        "Qué servicios de asesoría académica están disponibles para estudiantes de posgrado en la ESPE?":"Se ofrecen servicios de orientación en investigación, asesoría en la redacción de tesis y apoyo en la planificación académica y profesional.",
        "Cómo se promueve la investigación interdisciplinaria en la ESPE?":"Se promueve mediante la creación de grupos de investigación multidisciplinarios, proyectos conjuntos y la colaboración entre diferentes departamentos.",
        "Qué es el programa de becas para estancias de investigación en el extranjero en la ESPE?":"Es un programa que otorga becas para realizar estancias de investigación en instituciones académicas y de investigación fuera del país.",
        "Cómo se puede participar en el programa de estancias de investigación en el extranjero?":"Se puede participar presentando una solicitud a través del departamento de investigación, cumpliendo con los requisitos y criterios de selección.",
        "Qué tipo de formación en investigación se ofrece en la ESPE?":"Se ofrece formación a través de cursos de metodología de investigación, talleres, y seminarios especializados en técnicas y procesos de investigación.",
        "Cómo se promueve la participación en congresos y simposios científicos en la ESPE?":"Se promueve mediante la organización de eventos académicos, apoyo en la presentación de trabajos y participación en eventos científicos nacionales e internacionales.",
        "Qué es el programa de apoyo a la investigación aplicada en la ESPE?":"Es un programa que facilita la financiación y recursos para proyectos de investigación que buscan soluciones prácticas a problemas reales.",
        "Cómo se puede acceder a los recursos de investigación de la ESPE?":"Se puede acceder a través de la solicitud de fondos y recursos a través del departamento de investigación y cumpliendo con los requisitos establecidos.",
        "Qué tipo de investigación se realiza en el área de ciencias sociales en la ESPE?":"Se realiza investigación en áreas como psicología, sociología, educación, desarrollo comunitario y políticas públicas.",
        "Cómo se apoya la formación de investigadores en la ESPE?":"Se apoya mediante programas de capacitación, mentoría, y recursos para el desarrollo de proyectos y publicaciones científicas.",
        "Qué es el programa de becas para investigación en ciencias de la salud en la ESPE?":"Es un programa que otorga becas para realizar investigaciones en áreas relacionadas con la salud, medicina y biomedicina.",
        "Cómo se puede participar en los proyectos de investigación en ciencias de la salud en la ESPE?":"Se puede participar a través de la presentación de propuestas de investigación y colaboración con grupos de investigación en el área de salud.",
        "Qué tipo de actividades de formación en investigación se ofrecen a los estudiantes de la ESPE?":"Se ofrecen talleres, seminarios, cursos especializados y programas de capacitación en técnicas y metodologías de investigación.",
        "Cómo se promueve la colaboración entre la ESPE y la industria en investigación?":"Se promueve mediante la creación de alianzas estratégicas, proyectos conjuntos y la transferencia de tecnología y conocimiento.",
        "Qué es el programa de becas para el desarrollo de startups tecnológicas en la ESPE?":"Es un programa que ofrece becas y recursos para el desarrollo y lanzamiento de startups tecnológicas innovadoras por parte de estudiantes y exalumnos.",
        "Cómo se puede acceder a los recursos del programa de startups tecnológicas en la ESPE?":"Se puede acceder a través de la aplicación y selección en el programa, que ofrece apoyo financiero, mentoría y recursos para el desarrollo de startups.",
        "Qué tipo de proyectos de investigación se financian a través del programa de becas en la ESPE?":"Se financian proyectos de investigación en diversas áreas, incluyendo tecnología, salud, ciencias sociales y humanidades, que demuestren viabilidad y relevancia.",
        "Cómo se facilita la publicación de investigaciones en la ESPE?":"Se facilita mediante el apoyo en la redacción, revisión y envío de trabajos a revistas científicas, así como la organización de eventos para la divulgación de resultados.",
        "Qué es el programa de investigación en ciencias aplicadas en la ESPE?":"Es un programa que apoya la investigación en áreas prácticas y tecnológicas, con el objetivo de desarrollar soluciones innovadoras y aplicables en la industria.",
        "Cómo se promueve la investigación en ciencias naturales en la ESPE?":"Se promueve mediante la creación de laboratorios especializados, proyectos interdisciplinarios y colaboración con centros de investigación.",
        "Qué es el programa de becas para la realización de tesis en la ESPE?":"Es un programa que otorga becas para apoyar a los estudiantes en la investigación y desarrollo de sus tesis de grado o posgrado.",
        "Cómo se puede solicitar una beca para la realización de tesis en la ESPE?":"Se puede solicitar presentando una propuesta de tesis y cumpliendo con los requisitos establecidos por el programa de becas de tesis.",
        "Qué tipo de investigaciones se realizan en el área de ingeniería en la ESPE?":"Se realizan investigaciones en áreas como ingeniería de sistemas, ingeniería electrónica, ingeniería mecánica y tecnologías emergentes.",
        "Cómo se apoya la investigación en ingeniería en la ESPE?":"Se apoya mediante la provisión de recursos técnicos, equipos de laboratorio, y la colaboración con empresas del sector tecnológico e industrial.",
        "Qué es el programa de becas para estudios de doctorado en la ESPE?":"Es un programa que ofrece becas para estudiantes de doctorado, apoyando su investigación y desarrollo académico en áreas específicas de estudio.",
        "Cómo se puede acceder a las becas para estudios de doctorado en la ESPE?":"Se puede acceder mediante la presentación de una solicitud que incluya una propuesta de investigación y el cumplimiento de los requisitos académicos y de admisión.",
        "Qué tipo de investigación se realiza en el área de tecnología de la información en la ESPE?":"Se realiza investigación en áreas como desarrollo de software, inteligencia artificial, seguridad informática y redes de comunicación.",
        "Cómo se promueve la investigación en tecnología de la información en la ESPE?":"Se promueve mediante la creación de grupos de investigación especializados, acceso a laboratorios y colaboración con empresas tecnológicas.",
        "Cómo se fomenta la participación de mujeres en la investigación en la ESPE?":"Se fomenta a través de programas de mentoría, becas específicas y políticas de igualdad de género en el ámbito académico y de investigación.",
        "Qué es el sistema de apoyo a la transferencia de tecnología en la ESPE?":"Es un sistema que facilita la transferencia de tecnología desde la universidad hacia la industria, incluyendo la protección de propiedad intelectual y la comercialización de innovaciones.",
        "Qué programas de doble titulación ofrece la ESPE?":"La ESPE ofrece programas de doble titulación en colaboración con universidades extranjeras, permitiendo a los estudiantes obtener dos títulos académicos al finalizar sus estudios.",
        "Cómo se puede acceder a los laboratorios de computación en la ESPE?":"Los laboratorios de computación están disponibles para los estudiantes durante horarios establecidos y se accede presentando el carnet estudiantil.",
        "Qué es el sistema de gestión de calidad académica en la ESPE?":"Es un sistema que asegura la calidad de los programas académicos mediante evaluaciones continuas, auditorías y procesos de mejora.",
        "Cómo se promueve la investigación en ciencias sociales en la ESPE?":"La investigación en ciencias sociales se promueve a través de proyectos, publicaciones, seminarios y la participación en conferencias.",
        "Qué tipo de convenios internacionales tiene la ESPE?":"La ESPE tiene convenios con diversas universidades y organizaciones internacionales para promover el intercambio académico, la investigación y la cooperación.",
        "Cómo se pueden realizar prácticas profesionales en la ESPE?":"Los estudiantes pueden realizar prácticas profesionales inscribiéndose en el programa de prácticas y coordinando con el departamento correspondiente.",
        "Qué es el programa de estudios interdisciplinarios en la ESPE?":"Es un programa que permite a los estudiantes combinar estudios en diferentes disciplinas para obtener una formación más amplia y diversa.",
        "Cómo se promueve la responsabilidad social en la ESPE?":"La responsabilidad social se promueve a través de proyectos comunitarios, actividades de voluntariado y programas de sostenibilidad.",
        "Qué servicios de apoyo a la empleabilidad están disponibles en la ESPE?":"La ESPE ofrece talleres, ferias de empleo, asesoría en la elaboración de CV y preparación para entrevistas de trabajo.",
        "Cómo se puede acceder a las bases de datos científicas en la ESPE?":"Los estudiantes pueden acceder a las bases de datos científicas a través de la biblioteca digital de la universidad, utilizando su credencial institucional.",
        "Qué tipo de programas de formación en idiomas ofrece la ESPE?":"La ESPE ofrece programas de formación en idiomas como inglés, francés, alemán, chino y otros, a través de su centro de idiomas.",
        "Cómo se promueve el emprendimiento en la ESPE?":"El emprendimiento se promueve a través de incubadoras, aceleradoras de startups, concursos de ideas y programas de formación en negocios.",
        "Qué es el programa de movilidad académica internacional en la ESPE?":"Es un programa que permite a los estudiantes realizar parte de sus estudios en universidades extranjeras, facilitando la experiencia internacional.",
        "Cómo se puede acceder a los servicios de orientación vocacional en la ESPE?":"Los servicios de orientación vocacional están disponibles a través del departamento de bienestar estudiantil, ofreciendo asesoría personalizada y pruebas de aptitudes.",
        "Qué tipo de actividades deportivas se promueven en la ESPE?":"Se promueven actividades deportivas como fútbol, baloncesto, voleibol, atletismo y artes marciales, entre otras.",
        "Cómo se gestionan los programas de maestría en la ESPE?":"Los programas de maestría se gestionan a través de la escuela de posgrado, que coordina las inscripciones, el seguimiento académico y la defensa de tesis.",
        "Qué servicios de apoyo a estudiantes con discapacidad ofrece la ESPE?":"La ESPE ofrece servicios de apoyo como adaptaciones curriculares, accesibilidad en instalaciones y recursos tecnológicos adaptados.",
        "Qué es el programa de mentoría académica en la ESPE?":"Es un programa donde profesores y profesionales experimentados guían a los estudiantes en su desarrollo académico y profesional.",
        "Cómo se promueve la inclusión educativa en la ESPE?":"La inclusión educativa se promueve a través de políticas de equidad, programas de apoyo y becas para estudiantes de comunidades marginadas.",
        "Qué tipo de eventos culturales se realizan en la ESPE?":"Se realizan eventos culturales como festivales de música, exposiciones de arte, obras de teatro y proyecciones de cine.",
        "Cómo se pueden solicitar becas en la ESPE?":"Las becas se pueden solicitar a través del departamento de becas, presentando la documentación requerida y cumpliendo con los criterios establecidos.",
        "Qué servicios de atención psicológica están disponibles en la ESPE?":"La ESPE ofrece servicios de atención psicológica para estudiantes y personal, incluyendo terapia individual, grupal y talleres de manejo del estrés.",
        "Qué programas de actualización docente existen en la ESPE?":"La ESPE ofrece programas de actualización docente que incluyen cursos, talleres y seminarios para mejorar las competencias pedagógicas y tecnológicas de los profesores.",
        "Cómo se promueve la participación estudiantil en actividades extracurriculares en la ESPE?":"La participación se promueve a través de clubes, asociaciones estudiantiles, talleres y eventos organizados por la universidad.",
        "Qué es el programa de tutorías entre pares en la ESPE?":"Es un programa donde estudiantes avanzados apoyan a sus compañeros en temas académicos y de adaptación universitaria.",
        "Cómo se gestionan los servicios de salud en la ESPE?":"Los servicios de salud se gestionan a través del centro médico universitario, que ofrece atención médica, odontológica y de enfermería.",
        "Qué tipo de actividades de voluntariado se realizan en la ESPE?":"Se realizan actividades de voluntariado en áreas como educación, salud, medio ambiente y desarrollo comunitario.",
        "Qué es el programa de mentoría empresarial en la ESPE?":"Es un programa donde empresarios y profesionales guían a los estudiantes en el desarrollo de sus proyectos emprendedores.",
        "Cómo se promueve la investigación en ciencias naturales en la ESPE?":"La investigación en ciencias naturales se promueve a través de proyectos, publicaciones, colaboraciones internacionales y la participación en congresos.",
        "Qué servicios de apoyo a la investigación existen en la ESPE?":"La ESPE ofrece servicios de apoyo a la investigación como laboratorios, bibliotecas especializadas, financiamiento y asesoramiento técnico.",
        "Cómo se puede acceder a los servicios de comedor en la ESPE?":"Los servicios de comedor están disponibles para los estudiantes y se accede presentando el carnet estudiantil en los horarios establecidos.",
        "Qué tipo de actividades de desarrollo personal se promueven en la ESPE?":"Se promueven actividades de desarrollo personal como talleres de liderazgo, manejo del estrés, habilidades de comunicación y trabajo en equipo.",
        "Cómo se gestionan los servicios de transporte en la ESPE?":"Los servicios de transporte se gestionan a través de la administración universitaria, ofreciendo rutas dentro y fuera del campus.",
        "Qué es el programa de formación en habilidades técnicas en la ESPE?":"Es un programa que ofrece cursos y talleres en habilidades técnicas como programación, diseño gráfico, mecánica y más.",
        "Cómo se promueve la participación en eventos académicos en la ESPE?":"La participación se promueve a través de la difusión de convocatorias, financiamiento y apoyo logístico para asistir a conferencias, seminarios y congresos.",
        "Qué tipo de programas de intercambio cultural existen en la ESPE?":"Existen programas de intercambio cultural que permiten a los estudiantes participar en actividades y proyectos en colaboración con universidades extranjeras.",
        "Cómo se gestionan los programas de doctorado en la ESPE?":"Los programas de doctorado se gestionan a través de la escuela de posgrado, que coordina las inscripciones, el seguimiento académico y la defensa de tesis.",
        "Qué es el sistema de evaluación de desempeño docente en la ESPE?":"Es un sistema que evalúa el desempeño de los docentes mediante encuestas, observaciones de clases y revisión de resultados académicos.",
        "Cómo se puede acceder a los servicios de salud mental en la ESPE?":"Los servicios de salud mental están disponibles a través del centro médico universitario, que ofrece atención psicológica y psiquiátrica.",
        "Qué tipo de programas de liderazgo se realizan en la ESPE?":"Se realizan programas de liderazgo que incluyen talleres, conferencias y actividades prácticas para desarrollar habilidades de liderazgo entre los estudiantes.",
        "Cómo se promueve la participación en programas de voluntariado en la ESPE?":"La participación se promueve a través de la difusión de oportunidades, coordinación con organizaciones externas y reconocimiento de horas de servicio.",
        "Qué servicios de apoyo académico están disponibles para los estudiantes de la ESPE?":"La ESPE ofrece servicios de apoyo académico como tutorías, centros de aprendizaje y recursos digitales para mejorar el rendimiento académico.",
        "Cómo se puede acceder a los servicios de consejería académica en la ESPE?":"Los servicios de consejería académica están disponibles a través de citas programadas con asesores académicos, que ofrecen orientación sobre planes de estudio y opciones académicas.",
        "Qué tipo de programas de salud preventiva se realizan en la ESPE?":"Se realizan programas de salud preventiva que incluyen campañas de vacunación, revisiones médicas periódicas y talleres sobre hábitos saludables.",
        "Cómo se gestionan los programas de prácticas preprofesionales en la ESPE?":"Los programas de prácticas preprofesionales se gestionan a través del departamento de prácticas, que coordina la asignación de prácticas y el seguimiento de los estudiantes.",
        "Qué es el programa de formación en habilidades blandas en la ESPE?":"Es un programa que ofrece talleres y cursos para desarrollar habilidades blandas como comunicación, trabajo en equipo y resolución de problemas.",
        "Cómo se promueve la investigación interdisciplinaria en la ESPE?":"Se promueve a través de la creación de grupos de investigación interdisciplinarios, proyectos conjuntos y la organización de eventos científicos que favorezcan la colaboración entre disciplinas.",
        "Qué tipo de actividades académicas se realizan en la ESPE?":"Se realizan actividades académicas como conferencias, seminarios, talleres, investigaciones y proyectos colaborativos.",
        "Cómo se gestionan los servicios de asesoría para la investigación en la ESPE?":"Los servicios de asesoría para la investigación se gestionan a través del centro de investigación, que ofrece apoyo en la planificación, ejecución y publicación de proyectos.",
        "Qué es el programa de intercambio estudiantil en la ESPE?":"Es un programa que permite a los estudiantes realizar parte de sus estudios en universidades extranjeras, promoviendo el intercambio académico y cultural.",
        "Cómo se promueve el desarrollo de habilidades tecnológicas en la ESPE?":"Se promueve a través de cursos de capacitación, talleres prácticos y el uso de tecnologías avanzadas en el currículo académico.",
        "Qué servicios de atención a la diversidad cultural existen en la ESPE?":"Existen servicios de atención a la diversidad cultural que incluyen actividades culturales, asesoría y apoyo para estudiantes internacionales y de diferentes contextos culturales.",
        "Cómo se gestionan los programas de formación continua en la ESPE?":"Los programas de formación continua se gestionan a través de la oferta de cursos, talleres y certificaciones para profesionales en diversas áreas.",
        "Qué tipo de actividades de integración comunitaria se realizan en la ESPE?":"Se realizan actividades de integración comunitaria como proyectos de desarrollo local, programas de apoyo a comunidades vulnerables y eventos de colaboración con organizaciones locales.",
        "Cómo se accede a los recursos de la biblioteca digital en la ESPE?":"Se accede a través del portal en línea de la biblioteca, utilizando las credenciales institucionales para consultar libros, artículos y otros recursos académicos.",
        "Qué es el programa de investigación aplicada en la ESPE?":"Es un programa que se enfoca en la investigación con aplicaciones prácticas, buscando soluciones a problemas reales en colaboración con la industria y la comunidad.",
        "Cómo se promueve la participación en proyectos de innovación en la ESPE?":"Se promueve a través de concursos de innovación, apoyo a proyectos emprendedores y colaboración con centros de investigación y empresas.",
        "Qué tipo de actividades de enriquecimiento académico se realizan en la ESPE?":"Se realizan actividades como conferencias, talleres especializados, visitas a centros de investigación y eventos académicos para ampliar los conocimientos y habilidades de los estudiantes.",
        "Cómo se gestionan los servicios de asesoría para el desarrollo de carrera en la ESPE?":"Los servicios de asesoría para el desarrollo de carrera se gestionan a través del centro de orientación profesional, ofreciendo asesoramiento personalizado, talleres y ferias de empleo.",
        "Qué es el programa de formación en habilidades de comunicación en la ESPE?":"Es un programa que ofrece talleres y cursos para mejorar las habilidades de comunicación escrita y oral, esenciales para el desempeño académico y profesional.",
        "Cómo se promueve la investigación en ingeniería en la ESPE?":"Se promueve a través de proyectos de investigación aplicada, publicaciones en revistas especializadas, participación en congresos y colaboración con la industria.",
        "Qué servicios de apoyo a la innovación tecnológica existen en la ESPE?":"Existen servicios como asesoría en desarrollo de tecnología, incubadoras de startups y acceso a recursos técnicos y financieros para proyectos innovadores.",
        "Cómo se pueden realizar intercambios académicos en la ESPE?":"Los intercambios académicos se realizan mediante la coordinación con el departamento de relaciones internacionales, que gestiona acuerdos con universidades asociadas.",
        "Qué tipo de actividades de formación en habilidades de liderazgo se ofrecen en la ESPE?":"Se ofrecen actividades como talleres de liderazgo, cursos de gestión y proyectos de liderazgo estudiantil para desarrollar competencias de liderazgo entre los estudiantes.",
        "Cómo se promueve la participación en eventos científicos en la ESPE?":"Se promueve a través de la difusión de convocatorias, apoyo financiero para asistir a conferencias y la organización de eventos científicos en la universidad.",
        "Qué es el programa de apoyo a la investigación en ciencias aplicadas en la ESPE?":"Es un programa que apoya la investigación en ciencias aplicadas mediante financiamiento, recursos técnicos y colaboración con empresas y centros de investigación.",
        "Cómo se gestionan los programas de formación en competencias digitales en la ESPE?":"Los programas de formación en competencias digitales se gestionan a través de cursos, talleres y certificaciones en áreas como programación, diseño digital y análisis de datos.",
        "Qué tipo de actividades culturales se realizan en la ESPE?":"Se realizan actividades culturales como exposiciones de arte, conciertos, representaciones teatrales y festivales para enriquecer la vida cultural de la comunidad universitaria.",
        "Cómo se accede a las becas de investigación en la ESPE?":"Se accede a través de convocatorias específicas, presentando propuestas de investigación y cumpliendo con los requisitos establecidos para cada beca.",
        "Qué es el programa de apoyo a la internacionalización en la ESPE?":"Es un programa que facilita la colaboración internacional, el intercambio académico y la participación en proyectos globales para ampliar el alcance de la investigación y la formación.",
        "Cómo se gestionan los servicios de orientación para el estudio en el extranjero en la ESPE?":"Se gestionan a través del departamento de relaciones internacionales, que ofrece asesoría, información sobre programas de intercambio y apoyo en el proceso de aplicación.",
        "Qué tipo de actividades de formación en habilidades de resolución de problemas se ofrecen en la ESPE?":"Se ofrecen talleres y cursos prácticos que abordan técnicas de resolución de problemas, pensamiento crítico y toma de decisiones efectivas.",
        "Cómo se promueve la participación en proyectos de responsabilidad social en la ESPE?":"Se promueve a través de la integración de proyectos de responsabilidad social en el currículo, la colaboración con organizaciones comunitarias y la oferta de oportunidades de voluntariado.",
        "Qué servicios de apoyo a la escritura académica están disponibles en la ESPE?":"Se ofrecen servicios como talleres de escritura, tutorías personalizadas y recursos en línea para ayudar a los estudiantes a mejorar sus habilidades de escritura académica.",
        "Cómo se gestionan los programas de formación en habilidades de investigación en la ESPE?":"Se gestionan a través de cursos, talleres y seminarios especializados que brindan herramientas y técnicas avanzadas para realizar investigaciones efectivas.",
        "Qué es el programa de formación en habilidades de negociación en la ESPE?":"Es un programa que ofrece capacitación en técnicas de negociación, resolución de conflictos y estrategias de comunicación para mejorar las habilidades de negociación en contextos académicos y profesionales.",
        "Cómo se promueve la participación en actividades interdisciplinarias en la ESPE?":"Se promueve a través de la creación de proyectos colaborativos, eventos académicos conjuntos y el fomento de equipos de trabajo que integren diversas disciplinas.",
        "Qué tipo de servicios de asesoría para el desarrollo de proyectos de investigación se ofrecen en la ESPE?":"Se ofrecen servicios como asesoramiento en la formulación de proyectos, búsqueda de financiamiento, gestión de recursos y publicación de resultados.",
        "Cómo se gestionan los servicios de apoyo a la investigación en ciencias sociales en la ESPE?":"Se gestionan a través de la oferta de recursos especializados, asesoramiento en metodologías de investigación y apoyo en la publicación y difusión de investigaciones.",
        "Qué es el programa de formación en habilidades de gestión de proyectos en la ESPE?":"Es un programa que ofrece capacitación en técnicas de planificación, ejecución y control de proyectos, así como en el uso de herramientas y metodologías de gestión.",
        "Cómo se promueve la participación en proyectos de investigación en el ámbito de la ingeniería en la ESPE?":"Se promueve a través de la integración de proyectos de investigación en el currículo, la oferta de financiamiento y recursos para investigación, y la colaboración con la industria.",
        "Qué servicios de apoyo a la investigación en ciencias naturales existen en la ESPE?":"Existen servicios como acceso a laboratorios, equipos especializados, asesoramiento en investigación y apoyo en la publicación de resultados científicos.",
        "Cómo se pueden realizar intercambios internacionales en la ESPE?":"Los intercambios internacionales se realizan mediante la gestión de acuerdos con universidades extranjeras, facilitando la movilidad de estudiantes y docentes.",
        "Qué tipo de programas de formación en habilidades de trabajo en equipo se ofrecen en la ESPE?":"Se ofrecen programas de formación que incluyen talleres, actividades prácticas y cursos sobre técnicas de colaboración y gestión de equipos.",
        "Cómo se promueve la participación en actividades de investigación aplicada en la ESPE?":"Se promueve a través de la integración de proyectos de investigación aplicada en el currículo, el apoyo financiero y la colaboración con empresas y organizaciones.",
        "Qué servicios de apoyo a la escritura científica están disponibles en la ESPE?":"Se ofrecen servicios como talleres de redacción científica, asesoramiento en la estructura de artículos y apoyo en la revisión y publicación de trabajos científicos.",
        "Cómo se gestionan los programas de formación en habilidades de comunicación efectiva en la ESPE?":"Se gestionan a través de cursos, talleres y actividades prácticas que abordan técnicas de comunicación escrita y oral para mejorar la capacidad de expresión y presentación.",
        "Qué tipo de actividades de enriquecimiento cultural se realizan en la ESPE?":"Se realizan actividades como exposiciones de arte, eventos musicales, representaciones teatrales y talleres culturales para fomentar el desarrollo cultural de los estudiantes.",
        "Cómo se promueve la participación en conferencias y congresos en la ESPE?":"Se promueve a través de la difusión de convocatorias, la oferta de financiamiento para asistir a eventos y la organización de conferencias y congresos en la universidad.",
        "Qué es el programa de apoyo a la investigación en ciencias aplicadas en la ESPE?":"Es un programa que facilita recursos, financiamiento y colaboración para proyectos de investigación que tienen aplicaciones prácticas en áreas específicas de las ciencias aplicadas.",
        "Cómo se gestionan los servicios de asesoría para el desarrollo de habilidades de investigación en la ESPE?":"Se gestionan a través del centro de investigación, que ofrece formación, recursos y asesoría especializada en técnicas y metodologías de investigación.",
        "Qué servicios de apoyo a la investigación en ingeniería están disponibles en la ESPE?":"Se ofrecen servicios como laboratorios equipados, asesoramiento en proyectos de investigación y apoyo en la obtención de financiamiento para proyectos de ingeniería.",
        "Cómo se promueve la participación en proyectos de investigación interdisciplinarios en la ESPE?":"Se promueve mediante la formación de equipos de investigación interdisciplinarios, la organización de eventos científicos conjuntos y el fomento de colaboraciones entre diferentes áreas de conocimiento.",
        "Qué tipo de actividades de formación en habilidades de liderazgo se ofrecen en la ESPE?":"Se ofrecen talleres, cursos y actividades prácticas para desarrollar habilidades de liderazgo, incluyendo técnicas de gestión, motivación de equipos y toma de decisiones.",
        "Cómo se accede a los recursos de investigación en la ESPE?":"Se accede a través de la biblioteca digital, centros de investigación y plataformas especializadas en recursos académicos y científicos, utilizando las credenciales institucionales.",
        "Qué es el programa de formación en habilidades de comunicación en la ESPE?":"Es un programa que ofrece talleres y cursos para desarrollar habilidades de comunicación escrita y oral, fundamentales para el éxito académico y profesional.",
        "Cómo se gestionan los programas de formación en habilidades de investigación en la ESPE?":"Se gestionan a través de la oferta de cursos, talleres y seminarios que proporcionan herramientas y técnicas avanzadas para la investigación.",
        "Qué servicios de apoyo a la investigación en ciencias sociales existen en la ESPE?":"Se ofrecen servicios como asesoría en metodologías de investigación, acceso a bases de datos especializadas y apoyo en la publicación de estudios en ciencias sociales.",
        "Cómo se promueve la participación en proyectos de innovación en la ESPE?":"Se promueve a través de la organización de concursos de innovación, apoyo a emprendedores y la colaboración con centros de investigación y empresas innovadoras.",
        "Qué tipo de servicios de asesoría para el desarrollo de proyectos de investigación se ofrecen en la ESPE?":"Se ofrecen servicios de asesoría en la formulación de proyectos, búsqueda de financiamiento, gestión de recursos y publicación de resultados de investigación.",
        "Cómo se gestionan los programas de formación en competencias digitales en la ESPE?":"Se gestionan a través de la oferta de cursos, talleres y certificaciones en áreas como programación, análisis de datos y diseño digital.",
        "Qué tipo de actividades culturales se realizan en la ESPE?":"Se realizan actividades como exposiciones de arte, conciertos, representaciones teatrales y festivales para enriquecer la vida cultural de la comunidad universitaria.",
        "Cómo se accede a las becas de investigación en la ESPE?":"Se accede a través de convocatorias específicas, cumpliendo con los requisitos establecidos y presentando propuestas de investigación.",
        "Cuál es el proceso para solicitar una beca en la ESPE?":"El proceso incluye completar formularios específicos, demostrar méritos académicos y cumplir con los requisitos establecidos por el departamento de becas.",
        "Qué programas de idiomas se ofrecen en la ESPE?":"Se ofrecen programas de idiomas como inglés, francés y otros según la demanda estudiantil, con cursos regulares e intensivos disponibles.",
        "Cómo se promueve la investigación científica en la ESPE?":"La promoción incluye convocatorias de proyectos, financiamiento para investigación y colaboración con instituciones nacionales e internacionales.",
        "Qué servicios de transporte están disponibles para los estudiantes de la ESPE?":"Se disponen de buses universitarios que conectan el campus con puntos estratégicos de la ciudad y servicios de transporte privado a precios preferenciales para estudiantes.",
        "Qué es el programa de tutorías entre pares en la ESPE?":"Es un programa donde estudiantes avanzados ofrecen tutorías académicas y orientación a estudiantes de cursos inferiores, promoviendo el aprendizaje colaborativo.",
        "Cómo se gestionan las bibliotecas en la ESPE?":"Las bibliotecas ofrecen acceso a recursos físicos y digitales, servicios de préstamo, salas de estudio y capacitaciones en habilidades de investigación.",
        "Qué oportunidades de emprendimiento se ofrecen en la ESPE?":"Se promueven incubadoras de negocios, concursos de emprendimiento y asesoría para estudiantes interesados en desarrollar startups y proyectos innovadores.",
        "Cómo se fomenta la ética y la integridad académica en la ESPE?":"A través de políticas claras, programas de sensibilización, y medidas disciplinarias para prevenir el plagio y otras formas de fraude académico.",
        "Qué es el programa de formación en competencias digitales en la ESPE?":"Es un programa que capacita a estudiantes en el uso de herramientas digitales, programación básica y habilidades necesarias para la era digital.",
        "Cómo se realizan las prácticas de laboratorio en la ESPE?":"Las prácticas se realizan en laboratorios equipados con tecnología de punta, bajo la supervisión de docentes especializados en cada área académica.",
        "Qué actividades culturales se realizan en la ESPE durante el año?":"Se organizan festivales de música, danza, teatro, exposiciones artísticas y eventos que promueven la diversidad cultural dentro de la comunidad universitaria.",
        "Cómo se accede al sistema de correo electrónico institucional en la ESPE?":"El acceso se realiza mediante la asignación de cuentas de correo electrónico institucionales para estudiantes, docentes y personal administrativo.",
        "Qué programas de intercambio académico están disponibles para estudiantes de la ESPE?":"Se ofrecen programas de intercambio con universidades socias en diferentes países, permitiendo a los estudiantes cursar semestres académicos en el extranjero.",
        "Cómo se gestionan los programas de becas deportivas en la ESPE?":"Los programas se gestionan a través del departamento de deportes, ofreciendo apoyo financiero a atletas destacados que representan a la universidad en competencias deportivas.",
        "Qué es el programa de mentoría académica en la ESPE?":"Es un programa donde docentes o profesionales expertos orientan a estudiantes en aspectos académicos y profesionales, apoyando su desarrollo integral.",
        "Cómo se puede acceder al servicio de préstamo de libros en la biblioteca de la ESPE?":"El servicio se accede presentando el carnet estudiantil y cumpliendo con las normativas establecidas para el préstamo y devolución de libros.",
        "Qué oportunidades de networking se ofrecen a los estudiantes de la ESPE?":"Se realizan eventos de networking, ferias de empleo, conferencias con profesionales y alumni para facilitar conexiones y oportunidades laborales para los estudiantes.",
        "Cómo se realiza el proceso de titulación en la ESPE?":"Involucra la presentación y defensa de una tesis o proyecto de titulación, cumpliendo con los requisitos académicos y administrativos establecidos por la universidad.",
        "Qué es el programa de seguimiento de egresados en la ESPE?":"Es un programa que realiza seguimiento a los egresados para evaluar su inserción laboral, satisfacción con la formación recibida y recopilar retroalimentación para mejorar programas académicos.",
        "Cómo se promueve la participación en programas de intercambio cultural en la ESPE?":"La participación se promueve a través de eventos culturales, intercambio de tradiciones y costumbres, y colaboración con estudiantes internacionales en actividades conjuntas.",
        "Qué es el programa de orientación vocacional en la ESPE?":"Es un programa que ofrece asesoramiento profesional y psicológico a estudiantes para ayudarles en la elección de su carrera y planificación de su futuro profesional.",
        "Cómo se gestionan los programas de prácticas profesionales en empresas en la ESPE?":"Los programas se gestionan mediante convenios con empresas e instituciones, proporcionando a los estudiantes la oportunidad de aplicar sus conocimientos en entornos laborales reales.",
        "Qué servicios de tecnología educativa se ofrecen en la ESPE?":"Se ofrecen servicios como plataformas virtuales de aprendizaje, recursos digitales y laboratorios tecnológicos para el desarrollo de habilidades en áreas como la informática y la ingeniería.",
        "Cómo se puede acceder al sistema de wifi en el campus de la ESPE?":"El acceso se realiza mediante credenciales proporcionadas por la universidad, permitiendo conexión a internet en áreas designadas del campus y edificios universitarios.",
        "Qué es el programa de inserción laboral en la ESPE?":"Es un programa que facilita a los estudiantes y egresados el acceso a oportunidades de empleo, pasantías y prácticas profesionales a través de alianzas con empresas y sectores productivos.",
        "Cómo se fomenta el espíritu emprendedor en la ESPE?":"Se fomenta a través de cursos, talleres, concursos de emprendimiento, asesoría especializada y acceso a recursos para la creación y desarrollo de startups y negocios innovadores.",
        "Qué programas de educación ejecutiva se ofrecen en la ESPE?":"Se ofrecen programas de educación ejecutiva como MBA, diplomados y cursos cortos dirigidos a profesionales que desean actualizar y fortalecer sus habilidades gerenciales y técnicas.",
        "Cómo se realiza la evaluación del desempeño estudiantil en la ESPE?":"La evaluación se realiza mediante exámenes, trabajos prácticos, proyectos individuales y grupales, y participación en actividades académicas y extracurriculares.",
        "Qué es el programa de atención a la diversidad cultural en la ESPE?":"Es un programa que promueve la inclusión y el respeto por la diversidad cultural dentro de la comunidad universitaria, organizando actividades educativas y de integración intercultural.",
        "Cómo se gestionan los programas de asesoría para la inserción laboral en la ESPE?":"Los programas se gestionan a través de talleres de empleabilidad, orientación vocacional, actualización de CV y simulacros de entrevistas para preparar a los estudiantes para el mercado laboral.",
        "Qué servicios de apoyo psicológico se ofrecen en la ESPE?":"Se ofrecen servicios de asesoría psicológica individual y grupal, talleres de desarrollo personal y emocional, y programas de prevención y promoción de la salud mental.",
        "Cómo se promueve la investigación aplicada en la ESPE?":"Se promueve a través de la colaboración con empresas e instituciones para desarrollar proyectos de investigación que generen soluciones innovadoras y aplicables en diversos campos.",
        "Qué es el programa de apoyo a la innovación tecnológica en la ESPE?":"Es un programa que apoya iniciativas de investigación y desarrollo tecnológico, facilitando recursos, infraestructura y colaboración con el sector productivo para la transferencia de tecnología.",
        "Cómo se gestionan los programas de formación en competencias blandas en la ESPE?":"Los programas se gestionan a través de talleres y cursos especializados en habilidades blandas como comunicación efectiva, trabajo en equipo, liderazgo y gestión del tiempo.",
        "Qué es el programa de atención a la salud sexual y reproductiva en la ESPE?":"Es un programa que ofrece información, asesoría y servicios relacionados con la salud sexual y reproductiva, promoviendo prácticas saludables y la prevención de enfermedades.",
        "Cómo se promueve la participación en proyectos de responsabilidad social empresarial en la ESPE?":"La participación se promueve a través de alianzas con empresas que desarrollan proyectos de responsabilidad social, involucrando a estudiantes en actividades de voluntariado y acción social.",
        "Qué es el programa de desarrollo de competencias comunicativas en la ESPE?":"Es un programa que fortalece las habilidades de comunicación oral y escrita de los estudiantes, preparándolos para interactuar efectivamente en entornos académicos y profesionales.",
        "Cómo se gestionan los programas de desarrollo profesional en la ESPE?":"Los programas se gestionan a través de cursos, seminarios y conferencias que ofrecen actualización y formación en temas relevantes para el desarrollo profesional y la empleabilidad.",
        "Qué servicios de accesibilidad se ofrecen para estudiantes con discapacidad en la ESPE?":"Se ofrecen servicios como adaptaciones curriculares, asistencia personalizada, tecnología asistiva y acceso a infraestructura accesible para garantizar la inclusión y participación plena en la vida universitaria.",
        "Cómo se puede acceder al servicio de asistencia técnica en la ESPE?":"El servicio se accede solicitando soporte técnico a través de plataformas virtuales, help desk y centros de atención presencial para resolver problemas relacionados con tecnología y sistemas informáticos.",
        "Qué es el programa de desarrollo de habilidades para el empleo en la ESPE?":"Es un programa que prepara a los estudiantes y egresados para enfrentar los desafíos del mercado laboral, ofreciendo formación en habilidades técnicas y competencias profesionales demandadas por empleadores.",
        "Cómo se gestiona la movilidad estudiantil internacional en la ESPE?":"La movilidad estudiantil se gestiona a través de acuerdos bilaterales con universidades extranjeras, facilitando intercambios académicos que enriquecen la experiencia educativa y cultural de los estudiantes.",
        "Qué es el programa de formación en ética profesional en la ESPE?":"Es un programa que promueve valores éticos y principios de integridad en la práctica profesional, preparando a los estudiantes para enfrentar dilemas éticos y tomar decisiones responsables en su carrera."


    }

    preguntas_intermedias = {
        "Que hora es en Panama?": f"La hora en Panamá es {datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=-5))).strftime('%H:%M')}.",
        "Que hora es en Japon?": f"La hora en Japón es {datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=9))).strftime('%H:%M')}.",
        "Que hora es en Australia?": f"La hora en Sydney, Australia es {datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=10))).strftime('%H:%M')}.",
        "Cual es el color de una banana?": "Una banana madura es generalmente amarilla.",
        "Cual es el color de una naranja?": "Una naranja es de color naranja.",
        "Que animal es conocido como el rey de la selva?": "El león es conocido como el rey de la selva.",
        "Como se llama el animal mas grande del mundo?": "El animal más grande del mundo es la ballena azul.",
        "Cuanto es 5+7?": "5+7 es 12.",
        "Cual es el oceano mas grande del mundo?": "El océano más grande del mundo es el Océano Pacífico.",
        "Cual es el rio mas largo del mundo?": "El río más largo del mundo es el río Amazonas."
    }

    preguntas_complejas = {
        "Como funciona el ciclo del agua?": "El ciclo del agua describe cómo el agua se evapora de la superficie de la Tierra, se eleva a la atmósfera, se enfría y condensa en forma de lluvia o nieve y luego regresa a la superficie terrestre.",
        "Cual es la teoria de la relatividad?": "La teoría de la relatividad, desarrollada por Albert Einstein, incluye la relatividad especial y general, y describe cómo el espacio y el tiempo están interrelacionados y cómo la gravedad afecta el espacio-tiempo.",
        "Como se desarrolla una mariposa?": "Una mariposa pasa por cuatro etapas de desarrollo: huevo, larva (oruga), pupa (crisálida) y adulto.",
        "Que es la inteligencia artificial?": "La inteligencia artificial es un campo de la informática que se centra en la creación de sistemas capaces de realizar tareas que normalmente requieren inteligencia humana, como el aprendizaje, la toma de decisiones y el reconocimiento de patrones.",
        "Que es el cambio climatico?": "El cambio climático se refiere a los cambios a largo plazo en las temperaturas y los patrones climáticos, principalmente causados por actividades humanas como la quema de combustibles fósiles.",
        "Como se genera la energia solar?": "La energía solar se genera mediante la captura de la luz solar y su conversión en electricidad utilizando paneles solares o células fotovoltaicas.",
        "Que es la fotosintesis?": "La fotosíntesis es el proceso mediante el cual las plantas, las algas y algunas bacterias convierten la luz solar en energía química, produciendo oxígeno como subproducto.",
        "Que es la computacion cuantica?": "La computación cuántica es un área de la informática que utiliza principios de la mecánica cuántica para realizar cálculos que serían imposibles o muy difíciles para las computadoras clásicas.",
        "Como se origino el universo?": "La teoría más aceptada sobre el origen del universo es el Big Bang, que sugiere que el universo comenzó como un punto extremadamente caliente y denso que se expandió rápidamente.",
        "Que es el efecto invernadero?": "El efecto invernadero es el proceso por el cual ciertos gases en la atmósfera de la Tierra atrapan el calor, manteniendo la temperatura del planeta más cálida de lo que sería sin ellos."
    }

    if pregunta in preguntas_simples:
        return 'simple', preguntas_simples[pregunta]
    elif pregunta in preguntas_intermedias:
        return 'intermedia', preguntas_intermedias[pregunta]
    elif pregunta in preguntas_complejas:
        return 'compleja', preguntas_complejas[pregunta]

    if len(pregunta.split()) <= 3:
        return 'simple', None  
    elif len(pregunta.split()) <= 7:
        return 'intermedia', None  
    else:
        return 'compleja', None  

# Función para responder preguntas usando el índice y el modelo TF-IDF
def responder_pregunta(pregunta, index, vectorizer, df):
    pregunta_embedding = vectorizer.transform([pregunta]).toarray().astype('float32')
    
    _, I = index.search(pregunta_embedding, 1)
    indice_pregunta_mas_cercana = I[0][0]
    respuesta = df.iloc[indice_pregunta_mas_cercana]['Respuesta']
    return respuesta

# Función para iniciar el chatbot
def iniciar_chatbot():
    csv_path = 'Preguntas.csv'
    df = cargar_preguntas_respuestas(csv_path)
    index, vectorizer = crear_base_vectorial(df)

    while True:
        pregunta = input("Ingrese su pregunta (o 'salir' para terminar): ").strip()
        if pregunta.lower() == 'salir':
            break
        
        nivel, respuesta_predefinida = clasificar_pregunta(pregunta)
        
        if respuesta_predefinida:
            print(f"Respuesta: {respuesta_predefinida}")
        else:
            respuesta = responder_pregunta(pregunta, index, vectorizer, df)
            print(f"Respuesta: {respuesta}")

if __name__ == "__main__":
    iniciar_chatbot()
